### PR TITLE
Review rpc call msgs

### LINKED ISSUE #328: Review all RPC call help messages
All `zen-cli help "command"` messages should ideally include:
1. The command and it's possible arguments
2. A general description of what the command does
3. A list of all arguments, their types and if they're mandatory or optional
4. A result of the expected output of the command, if the result would be too long, an excerpt can be provided
5. A usage example using zen-cli
6. A usage example using JSON-RPC (curl)

After RPC calls that need improvement have been identified a PR with fixes should be created.

Example of a well written help message (except for the default port in the curl command being wrong):
```
getinfo                                                                                                                                                                       
Returns an object containing various state info.                                                                                                                              
                                                                                                                                                                              
Result:                                                                                                                                                                       
{                                                                                                                                                                             
  "version": xxxxx,           (numeric) the server version                                                                                                                    
  "protocolversion": xxxxx,   (numeric) the protocol version                                                                                                                  
  "walletversion": xxxxx,     (numeric) the wallet version                                                                                                                    
  "balance": xxxxxxx,         (numeric) the total Zcash balance of the wallet                                                                                                 
  "blocks": xxxxxx,           (numeric) the current number of blocks processed in the server                                                                                  
  "timeoffset": xxxxx,        (numeric) the time offset (deprecated; always 0)                                                                                                
  "connections": xxxxx,       (numeric) the number of connections                                                                                                             
  "proxy": "host:port",     (string, optional) the proxy used by the server                                                                                                   
  "difficulty": xxxxxx,       (numeric) the current difficulty                                                                                                                
  "testnet": true|false,      (boolean) if the server is using testnet or not                                                                                                 
  "keypoololdest": xxxxxx,    (numeric) the timestamp (seconds since GMT epoch) of the oldest pre-generated key in the key pool                                               
  "keypoolsize": xxxx,        (numeric) how many new keys are pre-generated                                                                                                   
  "unlocked_until": ttt,      (numeric) the timestamp in seconds since epoch (midnight Jan 1 1970 GMT) that the wallet is unlocked for transfers, or 0 if the wallet is locked
  "paytxfee": x.xxxx,         (numeric) the transaction fee set in ZEN/kB                                                                                                     
  "relayfee": x.xxxx,         (numeric) minimum relay fee for non-free transactions in ZEN/kB                                                                                 
  "errors": "..."           (string) any error messages                                                                                                                       
}                                                                                                                                                                             
                                                                                                                                                                              
Examples:                                                                                                                                                                     
> zen-cli getinfo                                                                                                                                                             
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getinfo", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:8232/        
```

### PR DESCRIPTION
**Pull request by cronicc**
closes HDE issue https://github.com/HorizenOfficial/zen/issues/328

### CODE REVIEW

**Comment by cronicc** [comment]
This is a rebase of https://github.com/HorizenOfficial/zen/pull/369 to clean up commit history, code is identical to it.

All credit goes to @luisantoniocrag for this contribution through HDE issue https://github.com/HorizenOfficial/zen/issues/328

For the additional reviewers please see the previous review done on https://github.com/HorizenOfficial/zen/pull/369

A separate PR with [review_rpc_call_msgs](https://github.com/HorizenOfficial/zen/tree/review_rpc_call_msgs) rebased onto [AddressIndexing_development](https://github.com/HorizenOfficial/zen/tree/AddressIndexing_development) will have to be done before the next scheduled release, tracked in issue https://github.com/HorizenOfficial/zen/issues/380.

File: src/rpc/net.cpp [hunk 1]
```diff
@@ -81,37 +87,40 @@ UniValue getpeerinfo(const UniValue& params, bool fHelp)
...
+            "    \"lastsend\": ttt,                      (numeric) the time in seconds since epoch (Jan 1 1970 GMT) of the last send\n"
+            "    \"lastrecv\": ttt,                      (numeric) the time in seconds since epoch (Jan 1 1970 GMT) of the last receive\n"
+            "    \"bytessent\": n,                       (numeric) the total bytes sent\n"
+            "    \"bytesrecv\": n,                       (numeric) the total bytes received\n"
+            "    \"conntime\": ttt,                      (numeric) the connection time in seconds since 1 Jan 1970 GMT\n"
+            "    \"timeoffset\": ttt,                    (numeric) the time offset in seconds\n"
+            "    \"pingtime\": n,                        (numeric) ping time\n"
+            "    \"pingwait\": n,                        (numeric) ping wait\n"
+            "    \"version\": v,                         (numeric) the protocol version of the peer\n"
+            "    \"subver\": \"/MagicBean:x.y.z[-v]/\",  (string) the user agent of the peer\n"
```
Comment (alsala) [inline src/rpc/net.cpp]: I am not sure of this. If we execute getpeerinfo via cli we have:
[...]
   "version": 170002,
   "subver": "/zen:2.0.23/",
[...]

Comment (cronicc) [reply src/rpc/net.cpp]: Addressed in https://github.com/HorizenOfficial/zen/pull/379/commits/728008a9b05269c2e338dfb33c11831aa24d32f6

**Review by albertog78 — APPROVED** [review]
