### PR TITLE
Review  and fix RPC call messages

### LINKED ISSUE #328: Review all RPC call help messages
All `zen-cli help "command"` messages should ideally include:
1. The command and it's possible arguments
2. A general description of what the command does
3. A list of all arguments, their types and if they're mandatory or optional
4. A result of the expected output of the command, if the result would be too long, an excerpt can be provided
5. A usage example using zen-cli
6. A usage example using JSON-RPC (curl)

After RPC calls that need improvement have been identified a PR with fixes should be created.

Example of a well written help message (except for the default port in the curl command being wrong):
```
getinfo                                                                                                                                                                       
Returns an object containing various state info.                                                                                                                              
                                                                                                                                                                              
Result:                                                                                                                                                                       
{                                                                                                                                                                             
  "version": xxxxx,           (numeric) the server version                                                                                                                    
  "protocolversion": xxxxx,   (numeric) the protocol version                                                                                                                  
  "walletversion": xxxxx,     (numeric) the wallet version                                                                                                                    
  "balance": xxxxxxx,         (numeric) the total Zcash balance of the wallet                                                                                                 
  "blocks": xxxxxx,           (numeric) the current number of blocks processed in the server                                                                                  
  "timeoffset": xxxxx,        (numeric) the time offset (deprecated; always 0)                                                                                                
  "connections": xxxxx,       (numeric) the number of connections                                                                                                             
  "proxy": "host:port",     (string, optional) the proxy used by the server                                                                                                   
  "difficulty": xxxxxx,       (numeric) the current difficulty                                                                                                                
  "testnet": true|false,      (boolean) if the server is using testnet or not                                                                                                 
  "keypoololdest": xxxxxx,    (numeric) the timestamp (seconds since GMT epoch) of the oldest pre-generated key in the key pool                                               
  "keypoolsize": xxxx,        (numeric) how many new keys are pre-generated                                                                                                   
  "unlocked_until": ttt,      (numeric) the timestamp in seconds since epoch (midnight Jan 1 1970 GMT) that the wallet is unlocked for transfers, or 0 if the wallet is locked
  "paytxfee": x.xxxx,         (numeric) the transaction fee set in ZEN/kB                                                                                                     
  "relayfee": x.xxxx,         (numeric) minimum relay fee for non-free transactions in ZEN/kB                                                                                 
  "errors": "..."           (string) any error messages                                                                                                                       
}                                                                                                                                                                             
                                                                                                                                                                              
Examples:                                                                                                                                                                     
> zen-cli getinfo                                                                                                                                                             
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getinfo", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:8232/        
```

### PR DESCRIPTION
**Pull request by luisantoniocrag**
close #328 

This PR reviews and edits ALL rpc call help messages.

### CODE REVIEW

**Review by sonzap006 — COMMENTED** [review]
n

**Review by sonzap006 — COMMENTED** [review]
Good

File: src/rpc/blockchain.cpp [hunk 1]
```diff
@@ -193,9 +195,11 @@ UniValue getbestblockhash(const UniValue& params, bool fHelp)
     if (fHelp || params.size() != 0)
         throw runtime_error(
             "getbestblockhash\n"
-            "\nReturns the hash of the best (tip) block in the longest block chain.\n"
+            "\nReturns the hash of the best (most recent) block in the longest block chain.\n"
```
Comment (cronicc) [inline src/rpc/blockchain.cpp]:
```suggestion
            "\nReturns the hash of the best (most recent) block in the active block chain.\n"
```
Best to word it like this, as with our penalty system for delayed block submission it's possible that the longest chain is not the active/best chain.

File: src/rpc/blockchain.cpp [hunk 2]
```diff
@@ -400,45 +416,60 @@ UniValue getblock(const UniValue& params, bool fHelp)
...
+            
             "\nResult (for verbose=0):\n"
-            "\"data\"             (string) A string that is serialized, hex-encoded data for block 'hash'.\n"
+            "\"data\"                               (string) a string that is serialized, hex-encoded data for block 'hash'\n"
+            
             "\nResult (for verbosity = 2):\n"
             "{\n"
-            "  ...,                     Same output as verbosity = 2.\n"
-            "  \"tx\" : [               (array of Objects) The transactions in the format of the getrawtransaction RPC.\n"
+            "  ...,                                 same output as verbosity = 2\n"
```
Comment (cronicc) [inline src/rpc/blockchain.cpp]:
```suggestion
            "  ...,                                 same output as verbosity = 1\n"
```

File: src/rpc/blockchain.cpp [hunk 3]
```diff
@@ -1142,8 +1203,17 @@ UniValue getglobaltips(const UniValue& params, bool fHelp)
...
+            "\nResult:\n"
+            "Global tips: n (numeric, global forks tips)\n"
+            "-----------------------\n"
+            "h(n (numeric, block height index)) \"hash\" (string, block hash) onFork[-] time[xxxxx (numeric, time)]\n"
+            "Ordered: ---------------\n"
+            "[\"hash\" (string, block hash) ]\n"
+            
             "\nExamples:\n"
             + HelpExampleCli("getglobaltips", "\"hash\"")
+            + HelpExampleRpc("getglobaltips", "\"hash\"")
```
Comment (cronicc) [inline src/rpc/blockchain.cpp]:
```suggestion
            + HelpExampleCli("getglobaltips", "")
            + HelpExampleRpc("getglobaltips", "")
```
Takes no arguments.

File: src/rpc/blockchain.cpp [hunk 4]
```diff
@@ -1077,8 +1130,16 @@ UniValue getblockfinalityindex(const UniValue& params, bool fHelp)
         throw runtime_error(
             "getblockfinalityindex \"hash\"\n"
             "\nReturns the minimum number of consecutive blocks a miner should mine from now in order to revert the block of given hash\n"
+
+            "\nArguments:\n"
+            "1. hash   (string, required)  the block hash"
+
+            "\"Result:\n"
+            "n         (numeric) number of consecutive blocks a miner should mine from now in order to revert the block of given hash\n"
```
Comment (cronicc) [inline src/rpc/blockchain.cpp]:
```suggestion
            "\nReturns the minimum number of consecutive blocks a miner would have to mine from now in order to revert the block of given hash\n"

            "\nArguments:\n"
            "1. hash   (string, required)  the block hash"

            "\"Result:\n"
            "n         (numeric) number of consecutive blocks a miner would have to mine from now in order to revert the block of given hash\n"
```

File: src/rpc/mining.cpp [hunk 5]
```diff
@@ -849,18 +887,22 @@ UniValue getblocksubsidy(const UniValue& params, bool fHelp)
...
             "\nResult:\n"
             "{\n"
-            "  \"miner\" : x.xxx           (numeric) The mining reward amount in ZEN.\n"
-            "  \"community\" : x.xxx        (numeric) The community fund amount in ZEN.\n"
-            "  \"securenodes\" : x.xxx        (numeric) The securenodes fund amount in ZEN (only if securenode HF fund is available).\n"
-            "  \"supernodes\" : x.xxx        (numeric) The supernodes fund amount in ZEN (only if supernode HF fund is available).\n"
+            "  \"miner\": xxxx,           (numeric) the mining reward amount in " + CURRENCY_UNIT + "\n"
+            "  \"community\": xxxx,       (numeric) the community fund amount in " + CURRENCY_UNIT + "\n"
+            "  \"securenodes\": xxxx,     (numeric) the securenodes fund amount in " + CURRENCY_UNIT + " (only if securenode HF fund is available)\n"
+            "  \"supernodes\": xxxx       (numeric) the supernodes fund amount in " + CURRENCY_UNIT + " (only if supernode HF fund is available)\n"
```
Comment (cronicc) [inline src/rpc/mining.cpp]:
```suggestion
            "  \"securenodes\": xxxx,     (numeric) the securenodes fund amount in " + CURRENCY_UNIT + "\n"
            "  \"supernodes\": xxxx       (numeric) the supernodes fund amount in " + CURRENCY_UNIT + "\n"
```
As the fork is active now this can be removed.

File: src/rpc/misc.cpp [hunk 6]
```diff
@@ -151,24 +153,28 @@ UniValue validateaddress(const UniValue& params, bool fHelp)
 {
     if (fHelp || params.size() != 1)
         throw runtime_error(
-            "validateaddress \"zcashaddress\"\n"
-            "\nReturn information about the given Zcash address.\n"
+            "validateaddress \"zenaddress\"\n"
+            "\nVerify an ZEN address is valid.\n"
```
Comment (cronicc) [inline src/rpc/misc.cpp]:
```suggestion
            "\nReturn information about the given ZEN address.\n"
```
Original wording was OK.

File: src/rpc/misc.cpp [hunk 7]
```diff
@@ -215,21 +221,23 @@ UniValue z_validateaddress(const UniValue& params, bool fHelp)
     if (fHelp || params.size() != 1)
         throw runtime_error(
             "z_validateaddress \"zaddr\"\n"
-            "\nReturn information about the given z address.\n"
+            "\nVerify an zaddress is valid.\n"
```
Comment (cronicc) [inline src/rpc/misc.cpp]:
```suggestion
            "\nReturn information about the given zaddress.\n"
```
Original wording was OK.

File: src/rpc/misc.cpp [hunk 8]
```diff
@@ -440,9 +450,17 @@ UniValue setmocktime(const UniValue& params, bool fHelp)
         throw runtime_error(
             "setmocktime timestamp\n"
             "\nSet the local time to given timestamp (-regtest only)\n"
+            
             "\nArguments:\n"
-            "1. timestamp  (integer, required) Unix seconds-since-epoch timestamp\n"
-            "   Pass 0 to go back to using the system time."
+            "1. timestamp  (numeric, required) Unix seconds-since-epoch timestamp\n"
+            "               pass 0 to go back to using the system tim."
```
Comment (cronicc) [inline src/rpc/misc.cpp]:
```suggestion
            "               pass 0 to go back to using the system time."
```

File: src/rpc/net.cpp [hunk 9]
```diff
@@ -81,37 +87,40 @@ UniValue getpeerinfo(const UniValue& params, bool fHelp)
...
-            "    \"startingheight\": n,       (numeric) The starting height (block) of the peer\n"
-            "    \"banscore\": n,             (numeric) The ban score\n"
-            "    \"synced_headers\": n,       (numeric) The last header we have in common with this peer\n"
-            "    \"synced_blocks\": n,        (numeric) The last block we have in common with this peer\n"
+            "    \"id\": n,                              (numeric) peer index\n"
+            "    \"addr\": \"host:port\",                (string) the ip address and port of the peer\n"
+            "    \"addrlocal\": \"ip:port\",             (string) local address\n"
+            "    \"services\":\"xxxxxxxxxxxxxxxx\",      (string) the services offered\n"
+            "    \"tls_established\": true|false,        (boolean) status of TLS connection\n"
+            "    \"tls_verified\": true|false,           (boolean) status of peer certificate. Will be true if a peer certificate can be verified with some trusted root certs \n"
```
Comment (cronicc) [inline src/rpc/net.cpp]:
```suggestion
            "    \"tls_verified\": true|false,           (boolean) status of peer certificate. True if the chain of trust of a peer certificate can be verified using the OS certificate store\n"
```

File: src/rpc/net.cpp [hunk 10]
```diff
@@ -225,8 +239,13 @@ UniValue disconnectnode(const UniValue& params, bool fHelp)
...
             "\nArguments:\n"
-            "1. \"node\"     (string, required) The node (see getpeerinfo for nodes)\n"
+            "1. \"node\"     (string, required) the node (see getpeerinfo for nodes)\n"
+            
+            "\nResult:\n"
+            "Nothing\n"
+            
             "\nExamples:\n"
             + HelpExampleCli("disconnectnode", "\"192.168.0.6:8233\"")
             + HelpExampleRpc("disconnectnode", "\"192.168.0.6:8233\"")
```
Comment (cronicc) [inline src/rpc/net.cpp]:
```suggestion
            + HelpExampleCli("disconnectnode", "\"192.168.0.6:9033\"")
            + HelpExampleRpc("disconnectnode", "\"192.168.0.6:9033\"")
```

File: src/rpc/net.cpp [hunk 11]
```diff
@@ -408,35 +432,38 @@ UniValue getnetworkinfo(const UniValue& params, bool fHelp)
...
-            "  \"networks\": [                          (array) information per network\n"
+            "  \"version\": xxxxx,                            (numeric) the version of the node as a numeric\n"
+            "  \"subversion\": \"/MagicBean:x.y.z[-v]/\",     (string) the subversion of the node, as advertised to peers\n"
+            "  \"protocolversion\": xxxxx,                    (numeric) the protocol version of the node\n"
+            "  \"localservices\": \"xxxxxxx\",                (string) the services supported by the node, as advertised in its version message\n"
+            "  \"timeoffset\": 0,                             (numeric) the time offset (deprecated; always 0)\n"
+            "  \"connections\": xxxxx,                        (numeric) the total number of open connections for the node\n"
+            "  \"tls_cert_verified\": true|flase,             (boolean) true if the certificate of the current node is verified\n"
+            "  \"networks\": [                                (array) an array of objects describing IPV4, IPV6 and Onion network interface states\n"
```
Comment (cronicc) [inline src/rpc/net.cpp]:
```suggestion
            "  \"networks\": [                                (array) an array of objects describing IPV4, IPV6 and Onion network status\n"
```

File: src/rpc/net.cpp [hunk 12]
```diff
@@ -480,18 +507,23 @@ UniValue setban(const UniValue& params, bool fHelp)
...
-                            + HelpExampleCli("setban", "\"192.168.0.6\" \"add\" 86400")
-                            + HelpExampleCli("setban", "\"192.168.0.0/24\" \"add\"")
-                            + HelpExampleRpc("setban", "\"192.168.0.6\", \"add\" 86400")
-                            );
+            "setban \"ip(/netmask)\" \"add|remove\" (bantime) (absolute)\n"
+            "\nAttempts add or remove a IP/Subnet from the banned list.\n"
+            
+            "\nArguments:\n"
+            "1. \"ip(/netmask)\" (string, required) the IP/Subnet (see getpeerinfo for nodes ip) with a optional netmask (default is /32 = single ip)\n"
+            "2. \"command\"      (string, required) 'add' to add a IP/Subnet to the list, 'remove' to remove a IP/Subnet from the list\n"
```
Comment (cronicc) [inline src/rpc/net.cpp]:
```suggestion
            "\nAttempts to add or remove an IP/Subnet from the banned list.\n"
            
            "\nArguments:\n"
            "1. \"ip(/netmask)\" (string, required) the IP/Subnet (see getpeerinfo for nodes ip) with an optional netmask (default is /32 = single ip)\n"
            "2. \"command\"      (string, required) 'add' to add an IP/Subnet to the list, 'remove' to remove an IP/Subnet from the list\n"
```

File: src/rpc/rawtransaction.cpp [hunk 13]
```diff
@@ -180,78 +180,78 @@ UniValue getrawtransaction(const UniValue& params, bool fHelp)
...
+            "  \"locktime\": ttt,                 (numeric) the lock time\n"
+            "  \"vin\": [                         (array of json objects)\n"
             "     {\n"
-            "       \"txid\": \"id\",    (string) The transaction id\n"
-            "       \"vout\": n,         (numeric) \n"
-            "       \"scriptSig\": {     (json object) The script\n"
-            "         \"asm\": \"asm\",  (string) asm\n"
-            "         \"hex\": \"hex\"   (string) hex\n"
+            "       \"txid\": \"id\",             (string) the transaction id\n"
+            "       \"vout\": n,                  (numeric) the output number\n"
```
Comment (cronicc) [inline src/rpc/rawtransaction.cpp]:
```suggestion
            "       \"vout\": n,                  (numeric) the output index\n"
```

File: src/rpc/rawtransaction.cpp [hunk 14]
```diff
@@ -180,78 +180,78 @@ UniValue getrawtransaction(const UniValue& params, bool fHelp)
...
+            "         \"addresses\": [            (json array of string)\n"
+            "           \"horizenaddress\"        (string) Horizen address\n"
             "           ,...\n"
             "         ]\n"
             "       }\n"
             "     }\n"
             "     ,...\n"
             "  ],\n"
-            "  \"vjoinsplit\" : [        (array of json objects, only for version >= 2)\n"
+            "  \"vjoinsplit\" : [                 (array of json objects, only for version >= 2)\n"
```
Comment (cronicc) [inline src/rpc/rawtransaction.cpp]:
```suggestion
            "  \"vjoinsplit\" : [                 (array of json objects, only for version 2 or -3)\n"
```

File: src/rpc/rawtransaction.cpp [hunk 15]
```diff
@@ -484,64 +496,64 @@ UniValue decoderawtransaction(const UniValue& params, bool fHelp)
...
+            "  \"locktime\": ttt,                                 (numeric) the lock time\n"
+            "  \"vin\": [                                         (array of json objects)\n"
             "     {\n"
-            "       \"txid\": \"id\",    (string) The transaction id\n"
-            "       \"vout\": n,         (numeric) The output number\n"
-            "       \"scriptSig\": {     (json object) The script\n"
-            "         \"asm\": \"asm\",  (string) asm\n"
-            "         \"hex\": \"hex\"   (string) hex\n"
+            "       \"txid\": \"id\",                             (string) the transaction id\n"
+            "       \"vout\": n,                                  (numeric) the output number\n"
```
Comment (cronicc) [inline src/rpc/rawtransaction.cpp]:
```suggestion
            "       \"vout\": n,                                  (numeric) the output index\n"
```

File: src/rpc/rawtransaction.cpp [hunk 16]
```diff
@@ -484,64 +496,64 @@ UniValue decoderawtransaction(const UniValue& params, bool fHelp)
...
+            "         \"addresses\": [                            (json array of string)\n"
+            "           \"xxxxxxxx\"                              (string) Horizen address\n"
             "           ,...\n"
             "         ]\n"
             "       }\n"
             "     }\n"
             "     ,...\n"
             "  ],\n"
-            "  \"vjoinsplit\" : [        (array of json objects, only for version >= 2)\n"
+            "  \"vjoinsplit\": [                                  (array of json objects, only for version >= 2)\n"
```
Comment (cronicc) [inline src/rpc/rawtransaction.cpp]:
```suggestion
            "  \"vjoinsplit\": [                                  (array of json objects, only for version 2 or -3)\n"
```

File: src/rpc/rawtransaction.cpp [hunk 17]
```diff
@@ -637,23 +651,23 @@ UniValue signrawtransaction(const UniValue& params, bool fHelp)
 #endif
 
             "\nArguments:\n"
-            "1. \"hexstring\"     (string, required) The transaction hex string\n"
-            "2. \"prevtxs\"       (string, optional) An json array of previous dependent transaction outputs\n"
-            "     [               (json array of json objects, or 'null' if none provided)\n"
+            "1. \"hexstring\"                      (string, required) the transaction hex string\n"
+            "2. \"prevtxs\"                        (string, optional) an json array of previous dependent transaction outputs\n"
```
Comment (cronicc) [inline src/rpc/rawtransaction.cpp]:
```suggestion
            "2. \"prevtxs\"                        (string, optional) a json array of previous dependent transaction outputs\n"
```

File: src/wallet/rpcdump.cpp [hunk 18]
```diff
@@ -746,15 +782,18 @@ UniValue z_exportkey(const UniValue& params, bool fHelp)
...
+            
             "\nResult:\n"
-            "\"key\"                  (string) The private key\n"
+            "\"key\"        (string) the private key\n"
+            
             "\nExamples:\n"
             + HelpExampleCli("z_exportkey", "\"myaddress\"")
-            + HelpExampleCli("z_importkey", "\"mykey\"")
-            + HelpExampleRpc("z_exportkey", "\"myaddress\"")
+            + HelpExampleCli("z_importkey", "\"zaddr\"")
```
Comment (cronicc) [inline src/wallet/rpcdump.cpp]:
```suggestion
            + HelpExampleCli("z_importkey", "\"zkey\"")
```

File: src/wallet/rpcwallet.cpp [hunk 19]
```diff
@@ -266,9 +274,14 @@ UniValue setaccount(const UniValue& params, bool fHelp)
...
-            "2. \"account\"         (string, required) MUST be set to the empty string \"\" to represent the default account. Passing any other string will result in an error.\n"
+            "1. \"horizenaddress\"  (string, required) the Horizen address to be associated with an account\n"
+            "2. \"account\"         (string, required) MUST be set to the empty string \"\" to represent the default account. Passing any other string will result in an error\n"
+
+            "\nResult:\n"
+            "Nothing\n"
+            
             "\nExamples:\n"
             + HelpExampleCli("setaccount", "\"t14oHp2v54vfmdgQ3v3SNuQga8JKHTNi2a1\" \"tabby\"")
             + HelpExampleRpc("setaccount", "\"t14oHp2v54vfmdgQ3v3SNuQga8JKHTNi2a1\", \"tabby\"")
```
Comment (cronicc) [inline src/wallet/rpcwallet.cpp]:
```suggestion
            + HelpExampleCli("setaccount", "\"horizenaddress\" \"tabby\"")
            + HelpExampleRpc("setaccount", "\"horizenaddress\", \"tabby\"")
```

**Review by cronicc — CHANGES_REQUESTED** [review]

**Comment by cronicc** [comment]
Hi @luisantoniocrag 

Thanks for doing this, I know how much work it involves. I've left a couple of change requests.

Please also change the RPC ports to 8231/18231 where we missed changing them originally.

https://github.com/luisantoniocrag/zen/blob/d41a781c7ded21c07a1e32919cba0d90fcc99da6/src/rpc/server.cpp#L613
https://github.com/luisantoniocrag/zen/blob/d41a781c7ded21c07a1e32919cba0d90fcc99da6/src/init.cpp#L554

**Comment by luisantoniocrag** [comment]
Thanks for reviewing @cronicc. I committed the suggested changes and update the rpc ports.

File: src/rpc/blockchain.cpp [hunk 20]
```diff
@@ -1076,9 +1129,17 @@ UniValue getblockfinalityindex(const UniValue& params, bool fHelp)
     if (fHelp || params.size() < 1 || params.size() > 2)
         throw runtime_error(
             "getblockfinalityindex \"hash\"\n"
-            "\nReturns the minimum number of consecutive blocks a miner should mine from now in order to revert the block of given hash\n"
+            "\nReturns the minimum number of consecutive blocks a miner would have to mine from now in order to revert the block of given hash\n"
+
+            "\nArguments:\n"
+            "1. hash   (string, required)  the block hash"
+
+            "\"Result:\n"
```
Comment (cronicc) [inline src/rpc/blockchain.cpp]:
```suggestion
            "1. hash   (string, required)  the block hash\n"

            "\nResult:\n"
```

File: src/rpc/net.cpp [hunk 21]
```diff
@@ -81,37 +87,40 @@ UniValue getpeerinfo(const UniValue& params, bool fHelp)
         throw runtime_error(
             "getpeerinfo\n"
             "\nReturns data about each connected network node as a json array of objects.\n"
+            
             "\nbResult:\n"
```
Comment (cronicc) [inline src/rpc/net.cpp]:
```suggestion
            "\nResult:\n"
```

**Review by cronicc — CHANGES_REQUESTED** [review]
@luisantoniocrag 
Hi, I've found two more small changes to make.

Once these are addressed, please rebase (squash) all of the commits from the change requests down to a single commit.

Here is a useful tutorial on squashing http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by luisantoniocrag** [comment]
@cronicc 
squashed 
https://github.com/HorizenOfficial/zen/pull/369/commits/cffe8ec17ba94d00ede271228055bf2bc1bead33

**Review by cronicc — APPROVED** [review]

**Comment by cronicc** [comment]
@luisantoniocrag Approved, thanks for the contribution!

I've changed the base branch of the PR as this will need additional review from a second developer before our next release window and everyone is busy working on zend_oo at the moment.

But it will eventually end up in development and master :)
